/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    articles: Article;
    portfolio: Portfolio;
    redirects: Redirect;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Pages du site : titres, méta et H1.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Ex. /contact/ ou /services/site-web/
   */
  path: string;
  pageType: 'classique' | 'service' | 'formation' | 'portfolio' | 'systeme';
  seoTitle?: string | null;
  metaDescription?: string | null;
  h1?: string | null;
  noindex?: boolean | null;
  formationContent?: {
    lead?: string | null;
    prix?: number | null;
    duree?: string | null;
    public?: string | null;
    prerequis?: string | null;
    objectifs?:
      | {
          objectif: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Le déroulé de la formation, module par module.
     */
    programme?:
      | {
          module: string;
          points?:
            | {
                point: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    modalites?: string | null;
    financement?: string | null;
    tarifs?:
      | {
          tarif: string;
          id?: string | null;
        }[]
      | null;
    faq?:
      | {
          question: string;
          reponse: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Bloc de contenu rédactionnel affiché sur la page (pages classiques, et en tête de corps des fiches service/formation).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles de blog. Renseignez le titre, le contenu et l’image à la une, puis le SEO (balise Title, meta description). Le slug (URL) se génère automatiquement depuis le titre. « Publier » met l’article en ligne : la page, les données structurées (Article) et le sitemap se mettent à jour tout seuls.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Titre principal (H1) de l’article.
   */
  title: string;
  /**
   * ex. geo-vs-aeo → /geo-vs-aeo/
   */
  slug: string;
  author?: string | null;
  /**
   * Ex. « SEO », « IA », « Réseaux sociaux ». Affichée sur l’article et utilisée dans les données structurées (articleSection). Optionnel.
   */
  category?: string | null;
  publishedDate?: string | null;
  /**
   * Visuel principal de l’article. Sert aussi d’aperçu au partage sur les réseaux (OpenGraph). Format paysage recommandé, idéalement 1200×630 px.
   */
  cover?: (number | null) | Media;
  /**
   * Décrit l’image pour l’accessibilité et le SEO. Prioritaire sur le alt du média.
   */
  coverAlt?: string | null;
  /**
   * Résumé court affiché dans les listes d’articles. Sert aussi de meta description si celle-ci est vide.
   */
  excerpt?: string | null;
  /**
   * Titre affiché dans Google (~50-60 caractères). « | ABCM » est ajouté automatiquement. Si vide, le titre de l’article est utilisé.
   */
  seoTitle?: string | null;
  /**
   * Résumé affiché sous le titre dans Google (~150-160 caractères). Si vide, l’extrait est utilisé.
   */
  metaDescription?: string | null;
  /**
   * À remplir seulement si le contenu est publié en priorité ailleurs. Laisser vide dans 99 % des cas : l’URL de l’article fait foi.
   */
  canonicalUrl?: string | null;
  /**
   * Coché : l’article passe en noindex et sort du sitemap (utile pour un contenu de service, une page légère…). Laisser décoché pour un article public normal.
   */
  noindex?: boolean | null;
  /**
   * Encart « En bref » (liste de points clés, en tête d’article).
   */
  summary?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Corps de l’article (titres H2/H3, paragraphes, listes, images, liens, citations…). C’est ce texte qui est publié et indexé.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Définit le « @type » des données structurées. Laisser « Article de blog » dans la plupart des cas.
   */
  schemaType?: ('BlogPosting' | 'Article' | 'NewsArticle') | null;
  /**
   * Mots-clés séparés par des virgules (ex. « SEO, IA, référencement »). Ajoutés aux données structurées. Optionnel.
   */
  keywords?: string | null;
  /**
   * Questions/réponses affichées en bas d’article ET envoyées à Google en données structurées (FAQPage), pour un affichage enrichi dans les résultats de recherche. Laisser vide si l’article n’a pas de FAQ.
   */
  faq?:
    | {
        question: string;
        /**
         * Réponse en texte simple (les données structurées n’acceptent pas la mise en forme).
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML historique conservé pour fidélité de rendu et repli.
   */
  legacyHtml?: string | null;
  contentEdited?: boolean | null;
  editedInAdmin?: boolean | null;
  legacyModified?: string | null;
  legacyCoverSrc?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images du site (couvertures d’articles, illustrations…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrit l’image pour l’accessibilité et le SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Fiches références / cas clients affichées dans le portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  /**
   * Ex. « Abry Arnold ». Sert de nom de la référence dans le back-office.
   */
  title: string;
  /**
   * Titre affiché en haut de la fiche. Si vide, le titre ci-dessus est utilisé.
   */
  h1?: string | null;
  /**
   * Résumé court affiché en introduction de la fiche (1 à 3 phrases).
   */
  summary?: string | null;
  /**
   * Le besoin, le contexte et les objectifs du client.
   */
  clientRequest?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * La solution mise en place, la démarche et les livrables.
   */
  ourResponse?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Une ou plusieurs images (mockups, captures, réalisations…). Ajoutez-en autant que nécessaire.
   */
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionnel. Ancien format « corps libre » (sections en titres H2). Utilisé uniquement si les champs structurés ci-dessus sont vides.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  promo?: {
    kind?: ('none' | 'service' | 'formation') | null;
    service?:
      | (
          | 'agence-web-strasbourg'
          | 'creation-site-ecommerce'
          | 'maintenance-site-web'
          | 'agence-payload'
          | 'referencement-strasbourg'
          | 'referencement-ia-geo'
          | 'audit-referencement'
          | 'community-management'
          | 'video-reseaux-sociaux'
          | 'videos-marque-employeur'
          | 'agence-sea'
          | 'agence-pub-ia'
          | 'marketing-externalise'
          | 'personal-branding'
        )
      | null;
    /**
     * Ex. formation-wordpress (le slug de la fiche formation, sans les slashs).
     */
    formation?: string | null;
  };
  /**
   * ex. abry-arnold → /portfolio/abry-arnold/
   */
  slug: string;
  /**
   * Seules les fiches « Publié » apparaissent sur le site et dans le sitemap.
   */
  status: 'draft' | 'published';
  /**
   * Épingle cette fiche sur la première ligne du portfolio. Jusqu’à 3 fiches à la une (les 3 rangs les plus bas si davantage sont cochées).
   */
  featured?: boolean | null;
  /**
   * Ordre d’affichage parmi les fiches à la une (1 = première). Laisser vide pour classer par titre.
   */
  featuredRank?: number | null;
  /**
   * Ex. « Stratégie Digitale », « Création de site »… (affiché en sur-titre).
   */
  projectType?: string | null;
  /**
   * Une ou plusieurs catégories. La première sert de catégorie principale (couleur / filtre).
   */
  categories?: ('site-internet' | 'formations' | 'strategie' | 'marketing' | 'publicite' | 'graphisme')[] | null;
  /**
   * Visuel principal : vignette de la grille et image du hero.
   */
  cover?: (number | null) | Media;
  logo?: (number | null) | Media;
  /**
   * Si vide, le titre de la fiche est utilisé.
   */
  seoTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Coché par défaut (politique du site) : la fiche est en noindex et exclue du sitemap. Décochez pour indexer cette fiche et l’ajouter au sitemap portfolio.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Redirections 301 / 302.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Ancienne URL, ex. /ancienne-page/
   */
  from: string;
  /**
   * Destination, ex. /nouvelle-page/
   */
  to: string;
  type?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Comptes autorisés à accéder au back-office.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  pageType?: T;
  seoTitle?: T;
  metaDescription?: T;
  h1?: T;
  noindex?: T;
  formationContent?:
    | T
    | {
        lead?: T;
        prix?: T;
        duree?: T;
        public?: T;
        prerequis?: T;
        objectifs?:
          | T
          | {
              objectif?: T;
              id?: T;
            };
        programme?:
          | T
          | {
              module?: T;
              points?:
                | T
                | {
                    point?: T;
                    id?: T;
                  };
              id?: T;
            };
        modalites?: T;
        financement?: T;
        tarifs?:
          | T
          | {
              tarif?: T;
              id?: T;
            };
        faq?:
          | T
          | {
              question?: T;
              reponse?: T;
              id?: T;
            };
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  category?: T;
  publishedDate?: T;
  cover?: T;
  coverAlt?: T;
  excerpt?: T;
  seoTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  noindex?: T;
  summary?:
    | T
    | {
        point?: T;
        id?: T;
      };
  content?: T;
  schemaType?: T;
  keywords?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  legacyHtml?: T;
  contentEdited?: T;
  editedInAdmin?: T;
  legacyModified?: T;
  legacyCoverSrc?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  h1?: T;
  summary?: T;
  clientRequest?: T;
  ourResponse?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  content?: T;
  promo?:
    | T
    | {
        kind?: T;
        service?: T;
        formation?: T;
      };
  slug?: T;
  status?: T;
  featured?: T;
  featuredRank?: T;
  projectType?: T;
  categories?: T;
  cover?: T;
  logo?: T;
  seoTitle?: T;
  metaDescription?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AstuceBlock".
 */
export interface AstuceBlock {
  titre?: string | null;
  contenu: string;
  variante?: ('astuce' | 'info' | 'retenir' | 'attention') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'astuce';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  texte: string;
  labelBouton: string;
  lien: string;
  couleur?: ('rose' | 'violet' | 'bleu' | 'vert' | 'ambre' | 'sombre') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlock".
 */
export interface ColumnsBlock {
  colonnes?:
    | {
        contenu?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}